language: node_js

node_js:
  - "0.10"

addons:
  firefox: "23.0"

services:
  - selenium

before_script:
  - "echo $BRANCH"
  - "echo $HEAD_BRANCH"
  - "echo $BASE_BRANCH"
  - "export DISPLAY=:99.0"
  - "/etc/init.d/xvfb start"

after_script:
  - "/etc/init.d/xvfb stop"

cache: true

build_timeout: 360

images:
  image:
    build:
      type : docker
      name: shippable/minv2
      tag: latest
      codePath: /src

# build_image: shippable/minv2

notifications:
  email:
    - exampleone@org.com
